package org.RealEstate.enumerator;

public enum Configuration {
	FREE_NB_OF_POST, POST_EXPIRY_DATE, MEDUIM_ACCOUNT_PAY, MEDUIM_ACCOUNT_NB_OF_POST, PREMIUM_ACCOUNT_PAY,
	PREMIUM_ACCOUNT_NB_OF_POST, PHONE_NUMBER, BROKER_NB_OF_POST, BOOST_DURATION, BOST_CASH, POST_BADGE_PAY
	

}
